### ISSUE TITLE
svg2ttf update 3.0.0 fixes IE issues

### ISSUE THREAD

**Issue by RobeeeJay** [nfroidure/gulp-svg2ttf#6]
svg2ttf 3.0.0 fixes a major issue with icon fonts and IE, details here:
https://github.com/fontello/svg2ttf/issues/37

Not sure if this just needs the package version to be bumped, or if there are more significant changes?

**Comment by nfroidure** [comment]
If any doubt, let's do a major version.

**Comment by RobeeeJay** [comment]
Major version bump with fix for IE ready to go:
https://github.com/nfroidure/gulp-svg2ttf/pull/7

**Comment by nfroidure** [comment]
Thanks. Just published it.
